### ISSUE TITLE
Transform example in README produces TypeError

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/koza#43]
When running the following example as shown in the README:
`$ koza transform --source examples/string/metadata.yaml`
the result is:
```
INFO:koza.koza_runner:No global table used for transform
Traceback (most recent call last):
  File "/home/harry/koza-env/bin/koza", line 8, in <module>
    sys.exit(main.app())
  File "/home/harry/koza-env/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/harry/koza-env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/koza-env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/harry/koza-env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/koza-env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/koza-env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/harry/koza-env/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/harry/koza-env/lib/python3.8/site-packages/koza/main.py", line 40, in transform
    transform_source(source, output_dir, output_format, global_table, local_table)
  File "/home/harry/koza-env/lib/python3.8/site-packages/koza/koza_runner.py", line 147, in transform_source
    source_config = SourceConfig(**yaml.safe_load(source_fh))
TypeError: __init__() missing 1 required positional argument: 'source_files'
```

Since koza is asking for a global table, is this a case where it wants a translation_table.yaml? Or is something just missing?

**Comment by kevinschaper** [comment]
Sorry, we broke it all.  

With the new version that we brought in this week, rather than pointing to a metadata file and then running all of the ingests, now the `--source` argument takes an individual source file config: 

```koza transform --global-table examples/translation_table.yaml --source examples/string/protein-links-detailed.yaml```

I'll get the documentation updated though!

**Comment by caufieldjh** [comment]
Thanks!
Though strangely enough, that example seems to produce the same result for me (i.e., `INFO:koza.koza_runner:No global table used for transform` ... all the way to the same TypeError)

**Comment by caufieldjh** [comment]
Looks like version 0.1.1 fixes this:
```
$ koza transform --global-table examples/translation_table.yaml --source examples/string/protein-links-detailed.yaml
INFO:koza.cli_runner:No local table used for transform
WARNING:koza.model.config.source_config:Could not load dataset description from metadata file
INFO:koza.io.reader.csv_reader:Finished processing 9 rows for protein-links-detailed
INFO:koza.io.reader.csv_reader:Finished processing 9 rows for protein-links-detailed
```

Thanks!
