### ISSUE TITLE
AttributeError: 'PrimaryFileConfig' object has no attribute '_field_type_map' when columns aren't defined

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/koza#45]
I'm trying to run Koza on Reactome mapping files within a script as follows:
` transform_source(config, output, "tsv", TRANSLATION_TABLE, None)`
where `config` is the path to a source yaml, e.g., 'chebi2reactome.yaml',
`output` is the path to the output directory,
and TRANSLATION_TABLE is the path to the translation_table.yaml, which is identical to that in the Koza repo here.

I'm consistently getting this error:
```
WARNING:koza.model.config.source_config:Could not load dataset description from metadata file
Traceback (most recent call last):
  File "run.py", line 164, in <module>
    cli()
  File "/home/harry/kg-env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/kg-env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/harry/kg-env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/kg-env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/kg-env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 63, in transform
    kg_transform(*args, **kwargs)
  File "/home/harry/kg-idg/kg_idg/transform.py", line 59, in transform
    t.run()
  File "/home/harry/kg-idg/kg_idg/transform_utils/reactome/reactome.py", line 56, in run
    self.parse(name, data_file, k)
  File "/home/harry/kg-idg/kg_idg/transform_utils/reactome/reactome.py", line 71, in parse
    transform_source(config, output, "tsv", TRANSLATION_TABLE, None)
  File "/home/harry/kg-env/lib/python3.8/site-packages/koza/cli_runner.py", line 143, in transform_source
    koza_source = Source(source_config)
  File "/home/harry/kg-env/lib/python3.8/site-packages/koza/model/source.py", line 51, in __init__
    field_type_map=config.field_type_map,
  File "/home/harry/kg-env/lib/python3.8/site-packages/koza/model/config/source_config.py", line 302, in field_type_map
    return self._field_type_map
AttributeError: 'PrimaryFileConfig' object has no attribute '_field_type_map'
```

It does in fact look like the PrimaryFileConfig class in source_config.py doesn't get assigned a '_field_type_map' attribute if columns aren't defined in the source yaml.

For reference, the input Reactome files don't have headers, so I haven't defined columns.
I suppose the workaround for now is to manually define columns within the input data?
Otherwise this could be related to #42.

**Comment by kevinschaper** [comment]
I think you're right that it's related to #42, Koza needs something to be the keys in the dictionary for the row that's returned. If nothing else, having a list of columns with your own aliases also helps the reader to catch any rows which have the wrong number of columns.

**Comment by kshefchek** [comment]
our csv reader is an extension of csv.DictReader in the std lib which defaults the first row as the headers - https://docs.python.org/3/library/csv.html#csv.DictReader, #42 should fix this
